# Generated by Django 5.0.3 on 2024-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_remove_images_category_alter_images_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
