# Generated by Django 5.0.3 on 2024-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
