# Generated by Django 5.0.3 on 2024-10-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0005_images_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='bulletsdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
